### ISSUE TITLE
How to prepare data and train model?

### ISSUE THREAD

**Issue by hao-liu-china** [JenningsL/PointRCNN#1]
Thank you for your great work. I hope you can release detailed descriptions about preparing data and training model.

**Comment by JenningsL** [comment]
Thanks for your interest. First of all, just a reminder, this is not the official implementation of PointRCNN. According to the author, the official one will become public available after April. Secondly, my implementation can only reproduce the performance of region proposal network, the RCNN network has much worse performance right now. 

This project is still on progress. I will add more detail about preparing data and training once the code is stable.

**Comment by hao-liu-china** [comment]
Thank you for your reply.

**Comment by hao-liu-china** [comment]
Sorry to bother you again. I have already read your code, and be interested in region proposal network.  Would you mind giving me your log and trained model?
My email is liuhao16c@nudt.edu.cn
Thank you.

**Comment by zl1994** [comment]
Can you tell me how much time it costs for one epoch?

**Comment by JenningsL** [comment]
> Sorry to bother you again. I have already read your code, and be interested in region proposal network. Would you mind giving me your log and trained model?
> My email is [liuhao16c@nudt.edu.cn](mailto:liuhao16c@nudt.edu.cn)
> Thank you.

I uploaded a log file and trained model for RPN here. https://drive.google.com/open?id=1gBChPg0sXdSL1YC3Qu_oSmMJW4BhkfD3.
You can test with it.

**Comment by JenningsL** [comment]
> Can you tell me how much time it costs for one epoch?

Training one epoch for RPN costs about 30 minutes.
