### ISSUE TITLE
The number of proposals after NMS

### ISSUE THREAD

**Issue by zl1994** [JenningsL/PointRCNN#3]
I found that most of the number of proposals after nms is less than 150, even the threshold of NMS was set to 0.9. And this is unfavorable for RCNN training. What is the possible reason?

**Comment by JenningsL** [comment]
How do you get the proposals after NMS? If you are using the nms_indices output of RPN, the average number of proposal is about 15 per frame. For RCNN training, it's recommended to use NMS code here https://github.com/JenningsL/PointRCNN/blob/master/dataset/frustum_dataset.py#L119
If it's still not enough,  you may consider augmenting the proposal boxes by perturbation.
