### ISSUE TITLE
'aug_scene/train_aug.txt' 这个文件在哪里？

### ISSUE THREAD

**Issue by Yaoxingtian** [JenningsL/PointRCNN#5]
你好！我发现代码中有些问题：
train_img_seg.py中
TRAIN_DATASET = Dataset(NUM_POINT, '/data/ssd/public/jlliu/Kitti/object', 'train', is_training=True, train_img_seg=True) ，少了channel ,train_img_seg参数不对，在Dataset中是use_aug_scene。

能不能麻烦告知'aug_scene/train_aug.txt' 这个文件是什么呢？
感谢！

**Comment by JenningsL** [comment]
train_img_seg.py 这个代码已经没有更新。如果你要使用，可以参考train_rpn.py 里面修改一下Dataset的参数。aug_scene 这个目录是用原作者的代码生成的, 请参考 https://github.com/sshaoshuai/PointRCNN，但是需要先把生成的class改成car, pedestrian 和 cyclist。如果不想使用，只需要把use_aug_scene置为False就行。
